name: Release APWorld
on:
  push:
    branches:
      - new-release-action
    tags:
      - '**'
jobs:
  release:
    uses: gerbiljames/ap-actions/.github/workflows/release-apworld.yml@standard-build-apworld
    with:
      apworld-path: worlds/pokemon_crystal_prerelease
      ap-version: '0.6.4'
      python-version: '3.12'
      prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc')}}
